### PR TITLE
feat(*): add data race detector for test and build

### PR DESCRIPTION
**Pull request by hezhizhen**
**What this PR does / why we need it**:

Add your description

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @bbbmj @supereagle @qianlei90 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by qianlei90** [comment]
这个已经有了，https://github.com/caicloud/golang-template-project/blob/master/Makefile#L90

**Comment by qianlei90** [comment]
Ref #17

**Comment by hezhizhen** [comment]
go test 和 go build 也会应用这个 GOFLAGS 吗

**Comment by qianlei90** [comment]
> go test 和 go build 也会应用这个 GOFLAGS 吗

go 子命令会从 GOFLAGS 里自动挑选可用的 flags 的

**Comment by supereagle** [comment]
@hezhizhen  Is it ok to close?

**Comment by hezhizhen** [comment]
> @hezhizhen Is it ok to close?

sure

**Pull request closed without merging**
